import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MyLayout from "./(components)/layout";
import { CartShoppingContextProvider } from "./context/CartShoppingContext";

export const metadata: Metadata = {
  title: "Mahdii first project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body>
        <CartShoppingContextProvider>
          <MyLayout>
            {children}
          </MyLayout>
        </CartShoppingContextProvider>
      </body>
    </html>
  );
}
